### ISSUE TITLE
Cannot use official issue tracker (youtrack) for "duplicates" plugin 

### ISSUE THREAD

**Issue by davidecavestro** [evgeny-goldin/gradle-plugins#13]
When I try to log into the issue tracker for the _duplicates_ plugin at http://evgeny-goldin.org/youtrack/issues/gp using my google account I always obtain a _User has been banned!_ message, hence I have no way to log in and add comments or file new issues

**Comment by evgeny-goldin** [comment]
Hi,
Yes, my YouTrack server has run into its limit of allowed user accounts. So feel free to use GitHub issue tracker.
