### ISSUE TITLE
Download Teamcity Dependancy from Evgenyg Repository Failing

### ISSUE THREAD

**Issue by Aravindakum** [evgeny-goldin/gradle-plugins#18]
Hello,

I am trying to build the plugin locally to use and while building it i get the build exception

Could not resolve all dependencies for configuration ':agent:compile'.

> Could not resolve teamcity:agent-api:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/agent-api/8.0.4/agent-api-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/agent-api/8.0.4/agent-api-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:servlet-api:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/servlet-api/8.0.4/servlet-api-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/servlet-api/8.0.4/servlet-api-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:common-api:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/common-api/8.0.4/common-api-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/common-api/8.0.4/common-api-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:annotations:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/annotations/8.0.4/annotations-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/annotations/8.0.4/annotations-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:util:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/util/8.0.4/util-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/util/8.0.4/util-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:jdom:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/jdom/8.0.4/jdom-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/jdom/8.0.4/jdom-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:spring:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/spring/8.0.4/spring-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/spring/8.0.4/spring-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:common-impl:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/common-impl/8.0.4/common-impl-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/common-impl/8.0.4/common-impl-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not resolve teamcity:idea-openapi:8.0.4.
>   Required by:
>       me.champeau.teamcity:agent:1.0.0-SNAPSHOT
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/teamcity/teamcity/idea-openapi/8.0.4/idea-openapi-8.0.4.pom'. Received status code 401 from server: Unauthorized
> Could not GET 'http://evgenyg.artifactoryonline.com/evgenyg/repo/teamcity/idea-openapi/8.0.4/idea-openapi-8.0.4.pom'. Received status code 401 from server: Unauthorized

**Comment by evgeny-goldin** [comment]
Hi, evgenyg.artifactoryonline.com repository is closed for anonymous access. You may need to switch to official JetBrains plugins.

**Comment by senkr132** [comment]
JetBrians seems to be not having any Groovy Plugin support for Build Runner.Is there a way we can get access to the above repository

**Comment by evgeny-goldin** [comment]
Please, send me an email to evgenyg@gmail.com, I'll provide you with user credentials for read-only access.
