### ISSUE TITLE
How to use latest Kotlin compiler

### ISSUE THREAD

**Issue by hmarggraff** [evgeny-goldin/gradle-plugins#5]
The current plugin (0.2) resolves the compiler version 0.4.68.
But I would rather use the latest version that I also use in Idea 12.0.
Specifying a local flatfile repository failed.
How would I do this?

**Comment by evgeny-goldin** [comment]
Hi,
I'll think of a way to make it customizable. Please, follow [this issue](http://evgeny-goldin.org/youtrack/issue/gp-52).

**Comment by evgeny-goldin** [comment]
Here's the snippet to use Kotlin `0.1-SNAPSHOT`:

```
apply plugin: 'kotlin'

buildscript {
    repositories { maven { url 'http://evgenyg.artifactoryonline.com/evgenyg/repo/' }}
    dependencies { 
        classpath ( 'com.github.goldin.plugins.gradle:kotlin:0.2-SNAPSHOT' ){ exclude group: 'org.jetbrains.kotlin' }
        classpath 'org.jetbrains.kotlin:kotlin-compiler:0.1-SNAPSHOT',
                  'org.jetbrains.kotlin:kdoc:0.1-SNAPSHOT'
    }
}

repositories {
    maven { url 'http://repository.jetbrains.com/kotlin/' }
}

dependencies {
    compile 'org.jetbrains.kotlin:kotlin-runtime:0.1-SNAPSHOT',
            'org.jetbrains.kotlin:kotlin-stdlib:0.1-SNAPSHOT'
}
```

**Comment by evgeny-goldin** [comment]
http://devnet.jetbrains.net/message/5473618

**Comment by evgeny-goldin** [comment]
'com.github.goldin.plugins.gradle:kotlin:0.2-SNAPSHOT' now depends on Kotlin v0.4.297.
